# Generated by Django 2.2.7 on 2019-11-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191121_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_min',
        ),
    ]
